/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package batch.guide;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
public class BatchProcessTest {

    @Test
	void contextLoads() {
	}
}
