version: '3.1'

services:
  postgres-db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dev
    volumes:
      - ./docker/volumes/postgres:/var/lib/postgresql/data
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/10-schema.sql
      - ./src/main/resources/data.sql:/docker-entrypoint-initdb.d/20-data.sql
    ports:
      - "5432:5432"
  
  rabbitmq:
    image: rabbitmq:3.8.9-management
    container_name: rabbit-docker
    restart: unless-stopped
    ports:
      - "5671:5671"
      - "5672:5672"
      - "15672:15672"
    